---
- hosts: all
  become: yes
  become_user: root
  user: ubuntu
  tasks:
    - name: Update repositories cache and install "docker-compose" package
      apt:
        name: docker-compose
        state: present # declerative
        update_cache: yes
#tag of the ec2 instance // upload file to server destination  copy and with item 
- hosts: Monitor_main
  become: yes
  become_user: root
  user: ubuntu
  tasks:
    - name: Copy docker-compose-main.yml & prometheus.yaml to remote /home/ubuntu/
      copy: src={{ item.src }} dest={{ item.dest }} mode=0644 owner=ubuntu
      with_items:
        - { src: 'docker-compose-main.yml', dest: '/home/ubuntu/docker-compose.yml'}
        - { src: 'prometheus.yml', dest: '/home/ubuntu/prometheus.yml'}
    - name: Run docker-compose in /home/ubuntu
      become: True
      shell:
        cmd: "docker-compose up -d"
        chdir: /home/ubuntu/

- hosts: Monitor_exporter
  become: yes
  become_user: root
  user: ubuntu
  tasks:
    - name: Copy docker-compose-exporter.yml to remote /home/ubuntu/docker-compose.yml
      copy:
        src: docker-compose-exporter.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name: Run docker-compose in /home/ubuntu
      become: True
      shell:
        cmd: "docker-compose up -d"
        chdir: /home/ubuntu/
